#!/usr/bin/env python

#
#   Vex Robotics Magnet Roomba Thing
#   This is the higher-level control code for the vacuum.
#   This manages mapping, GPS, and image processing.
#
#
#	TODO:
#		- Figure out GPS, mapping
#		- Figure out serial commands
# 		- Figure out serial connection to robot
# 		- Test try-catch to fix (or at least find) serial errors
# 		- Move all config variables to a .json or something
#		- venv
#
#
#


# imports
from os import error	# i guess this is autogenerated?
from serial.serialutil import SerialException

import gpiozero			# GPIO control
import serial			# serial communication with vex brain
import json



# set up serial connection to the vex brain
BRAIN_PORT = '/dev/ttyUSB0' 	# brain serial port
BRAIN_SERIAL_SPEED = 9600		# TODO: set this to the correct value

try: 
	brain = serial.Serial(BRAIN_PORT, BRAIN_SERIAL_SPEED, timeout = 0.1)

except SerialException as error:
	print('Serial Error (SerialExpection) {0}'.format(error))

	